package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"flow-test-go/internal/aibuilder"
	"flow-test-go/internal/project"

	"github.com/gin-gonic/gin"
)

func (s *Server) listAISessions(c *gin.Context) {
	p, ok := s.requireProject(c)
	if !ok {
		return
	}
	sessions, err := p.ListAISessions()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"sessions": sessions})
}

func (s *Server) createAISession(c *gin.Context) {
	p, ok := s.requireProject(c)
	if !ok {
		return
	}
	var body struct {
		Session map[string]any `json:"session"`
	}
	_ = c.ShouldBindJSON(&body)
	title := ""
	if body.Session != nil {
		if value, ok := body.Session["title"].(string); ok {
			title = value
		}
	}
	session, err := p.CreateAISession(title)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"session": session})
}

func (s *Server) getAISession(c *gin.Context) {
	p, ok := s.requireProject(c)
	if !ok {
		return
	}
	session, err := p.LoadAISession(c.Param("session_id"))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			c.JSON(http.StatusNotFound, gin.H{"detail": "AI 会话不存在"})
			return
		}
		c.JSON(http.StatusBadRequest, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"session": session})
}

func (s *Server) putAISession(c *gin.Context) {
	p, ok := s.requireProject(c)
	if !ok {
		return
	}
	var body struct {
		Session map[string]any `json:"session"`
	}
	if err := c.ShouldBindJSON(&body); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"detail": err.Error()})
		return
	}
	session, err := p.SaveAISession(c.Param("session_id"), body.Session)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"session": session})
}

func (s *Server) deleteAISession(c *gin.Context) {
	p, ok := s.requireProject(c)
	if !ok {
		return
	}
	if err := p.DeleteAISession(c.Param("session_id")); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			c.JSON(http.StatusNotFound, gin.H{"detail": "AI 会话不存在"})
			return
		}
		c.JSON(http.StatusBadRequest, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"ok": true})
}

func (s *Server) clearAISessions(c *gin.Context) {
	p, ok := s.requireProject(c)
	if !ok {
		return
	}
	deleted, err := p.ClearAISessions()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"deleted": deleted})
}

func (s *Server) newAIBuilder() *aibuilder.Builder {
	return aibuilder.NewBuilderWithConfig(s.aiBuilderConfig())
}

func (s *Server) aiBuilderConfig() aibuilder.Config {
	settings, err := project.LoadSettings()
	if err != nil {
		return aibuilder.DefaultConfig()
	}
	return aibuilder.ConfigFromSettings(settings)
}

func (s *Server) aiDraft(c *gin.Context) {
	if _, ok := s.requireProject(c); !ok {
		return
	}
	state := parseAIState(c)
	builder := s.newAIBuilder()
	draft, err := builder.BuildDraft(c.Request.Context(), aiStateMessage(state))
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"draft": draft})
}

func (s *Server) aiDraftStream(c *gin.Context) {
	p, ok := s.requireProject(c)
	if !ok {
		return
	}
	state := parseAIState(c)
	builder := s.newAIBuilder()
	draft, err := builder.BuildDraft(c.Request.Context(), aiStateMessage(state))
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	_ = saveDraftToAISession(p, c.Param("session_id"), draft, state)
	c.Header("Content-Type", "text/event-stream")
	c.Header("Cache-Control", "no-cache")
	c.Header("X-Accel-Buffering", "no")
	status := aiDraftStatusPayload(draft)
	writeSSE(c, "status", gin.H{"message": status["start_message"], "metadata": status["metadata"]})
	writeSSE(c, "message", gin.H{"content": status["content"], "metadata": status["metadata"]})
	writeSSE(c, "draft", gin.H{"draft": draft})
	writeSSE(c, "usage", gin.H{"usage": gin.H{"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0, "estimated": true}})
	writeSSE(c, "done", gin.H{"status": "completed", "message": status["done_message"], "summary": status["summary"], "metadata": status["metadata"]})
}

func aiDraftStatusPayload(draft map[string]any) gin.H {
	metadata, _ := draft["metadata"].(map[string]any)
	builder, _ := metadata["builder"].(string)
	if builder == "go-model-http" {
		return gin.H{
			"start_message": "Go AI Builder model generation completed",
			"done_message":  "Go AI Builder completed",
			"content":       "模型已生成可应用的 JS 流程草稿。",
			"summary":       "Draft generated by configured HTTP model provider and validated by Go graph patch compile.",
			"metadata":      metadata,
		}
	}
	content := "未配置可用模型时，Go 运行时已生成一个可应用的 JS 流程骨架。"
	if metadata["model_error"] != nil {
		content = "模型调用未成功，Go 运行时已回退生成一个可应用的 JS 流程骨架。"
	}
	return gin.H{
		"start_message": "Go fallback AI Builder started",
		"done_message":  "Go fallback AI Builder completed",
		"content":       content,
		"summary":       "Local JS flow skeleton generated by Go fallback builder.",
		"metadata":      metadata,
	}
}

func parseAIState(c *gin.Context) map[string]any {
	raw := c.PostForm("state")
	if raw == "" {
		var body map[string]any
		if err := c.ShouldBindJSON(&body); err == nil && body != nil {
			return body
		}
		return map[string]any{}
	}
	var state map[string]any
	if err := json.Unmarshal([]byte(raw), &state); err != nil {
		return map[string]any{}
	}
	return state
}

func aiStateMessage(state map[string]any) string {
	if value, ok := state["message"].(string); ok {
		return value
	}
	if history, ok := state["history"].([]any); ok && len(history) > 0 {
		if last, ok := history[len(history)-1].(map[string]any); ok {
			if content, ok := last["content"].(string); ok {
				return content
			}
		}
	}
	return ""
}

func saveDraftToAISession(p interface {
	LoadAISession(string) (map[string]any, error)
	SaveAISession(string, map[string]any) (map[string]any, error)
}, id string, draft map[string]any, state map[string]any) error {
	session, err := p.LoadAISession(id)
	if err != nil {
		return err
	}
	session["draft"] = draft
	session["updated_at"] = time.Now().UTC().Format(time.RFC3339)
	if message := aiStateMessage(state); message != "" {
		session["last_message"] = message
	}
	session["build_state"] = buildStateWithSummary(session["build_state"], state, session)
	_, err = p.SaveAISession(id, session)
	return err
}

func saveToolLoopStateToAISession(p interface {
	LoadAISession(string) (map[string]any, error)
	SaveAISession(string, map[string]any) (map[string]any, error)
}, id string, state map[string]any, result aibuilder.ToolLoopResult) error {
	session, err := p.LoadAISession(id)
	if err != nil {
		return err
	}
	session["updated_at"] = time.Now().UTC().Format(time.RFC3339)
	if message := aiStateMessage(state); message != "" {
		session["last_message"] = message
	}
	buildState := buildStateWithSummary(session["build_state"], state, session)
	lastToolLoop := map[string]any{
		"status":     result.Status,
		"summary":    result.Summary,
		"tool_calls": result.ToolCalls,
	}
	if len(result.Trace) > 0 {
		trace := result.Trace
		if len(trace) > 100 {
			trace = trace[len(trace)-100:]
		}
		lastToolLoop["trace"] = trace
	}
	buildState["last_tool_loop"] = lastToolLoop
	if len(result.Rejections) > 0 {
		existing := anySliceValue(buildState["rejected_operations"])
		for _, item := range result.Rejections {
			existing = append(existing, item)
		}
		if len(existing) > 50 {
			existing = existing[len(existing)-50:]
		}
		buildState["rejected_operations"] = existing
	}
	session["build_state"] = buildState
	_, err = p.SaveAISession(id, session)
	return err
}

func buildStateWithSummary(current any, state map[string]any, session map[string]any) map[string]any {
	buildState := mapValue(current)
	messages := aibuilder.BuildDirectBuildMessages(state, docsFromState(state), session)
	if len(messages) >= 2 {
		buildState["last_init_summary"] = messages[1].Content
	}
	return buildState
}

func docsFromState(state map[string]any) []map[string]any {
	raw := anySliceValue(state["documents"])
	out := make([]map[string]any, 0, len(raw))
	seen := map[string]bool{}
	for _, item := range raw {
		if doc, ok := item.(map[string]any); ok {
			out = append(out, doc)
			if name, ok := doc["name"].(string); ok {
				seen[name] = true
			}
		}
	}
	for _, doc := range selectedGraphSkillDocs(state) {
		name, _ := doc["name"].(string)
		if name != "" && seen[name] {
			continue
		}
		out = append(out, doc)
		seen[name] = true
	}
	return out
}

func selectedGraphSkillDocs(state map[string]any) []map[string]any {
	root := findGraphSkillsRoot()
	if root == "" {
		return nil
	}
	query := strings.ToLower(graphSkillQuery(state))
	selected := []string{"DOC.md"}
	addByNeed := func(need bool, rels ...string) {
		if need {
			selected = append(selected, rels...)
		}
	}
	addByNeed(needsScriptDocs(query), "script/DOC.md", "script/script_js/DOC.md", "script/script_js_exec/DOC.md", "test/assert_check/DOC.md", "test/test_result/DOC.md")
	addByNeed(containsAny(query, "api", "http", "https", "request", "json", "form", "接口", "请求", "表单", "序列化"), "api/DOC.md", "api/api_request/DOC.md", "api/api_json_serialize/DOC.md", "api/api_form_serialize/DOC.md")
	addByNeed(containsAny(query, "regex", "regexp", "正则", "提取", "匹配"), "regex/DOC.md", "regex/regex_find/DOC.md")
	addByNeed(containsAny(query, "click", "type", "hotkey", "scroll", "drag", "点击", "输入", "快捷键", "滚动", "拖拽"), "action/DOC.md")
	addByNeed(containsAny(query, "image", "picture", "vision", "ocr", "text", "mask", "找图", "图片", "视觉", "识别", "文字", "遮罩"), "vision/DOC.md", "ocr/DOC.md")
	addByNeed(containsAny(query, "wait", "delay", "appear", "vanish", "等待", "出现", "消失"), "wait/DOC.md")
	addByNeed(containsAny(query, "rdp", "vnc", "pve", "vmware", "device", "设备", "远程", "虚拟机"), "device/DOC.md", "interaction/DOC.md")
	addByNeed(containsAny(query, "if", "loop", "sequence", "try", "catch", "流程", "分支", "循环", "异常"), "flow/DOC.md")
	for _, nodeType := range graphNodeTypes(state["current_graph"]) {
		if rel := docForNodeType(root, nodeType); rel != "" {
			selected = append(selected, rel)
		}
	}
	return readGraphSkillDocs(root, selected, 12)
}

func graphSkillQuery(state map[string]any) string {
	var parts []string
	parts = append(parts, stringValue(state["message"]))
	for _, item := range anySliceValue(state["documents"]) {
		doc, ok := item.(map[string]any)
		if !ok {
			continue
		}
		parts = append(parts, stringValue(doc["name"]), stringValue(doc["text"]), stringValue(doc["content"]))
	}
	for _, typ := range graphNodeTypes(state["current_graph"]) {
		parts = append(parts, typ)
	}
	data, _ := json.Marshal(mapValue(state["form_values"]))
	parts = append(parts, string(data))
	return strings.Join(parts, "\n")
}

func needsScriptDocs(query string) bool {
	return containsAny(query,
		"script", "javascript", "js", "logic", "loop", "repeat", "calculate", "complex", "simplify",
		"脚本", "复杂", "简化", "循环", "重复", "计算", "组合判断", "逻辑",
	)
}

func containsAny(text string, needles ...string) bool {
	for _, needle := range needles {
		if strings.Contains(text, strings.ToLower(needle)) {
			return true
		}
	}
	return false
}

func graphNodeTypes(value any) []string {
	graph := mapValue(value)
	nodes := anySliceValue(graph["nodes"])
	out := make([]string, 0, len(nodes))
	for _, item := range nodes {
		node, ok := item.(map[string]any)
		if !ok {
			continue
		}
		typ := stringValue(node["type"])
		if typ != "" {
			out = append(out, typ)
		}
	}
	return out
}

func docForNodeType(root string, nodeType string) string {
	var found string
	_ = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || filepath.Base(path) != "node.json" {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		var node map[string]any
		if err := json.Unmarshal(data, &node); err != nil {
			return nil
		}
		if stringValue(node["type"]) != nodeType {
			return nil
		}
		docPath := filepath.Join(filepath.Dir(path), "DOC.md")
		if _, err := os.Stat(docPath); err == nil {
			if rel, err := filepath.Rel(root, docPath); err == nil {
				found = filepath.ToSlash(rel)
			}
		}
		return filepath.SkipAll
	})
	return found
}

func readGraphSkillDocs(root string, rels []string, limit int) []map[string]any {
	out := []map[string]any{}
	seen := map[string]bool{}
	for _, rel := range rels {
		if rel == "" || seen[rel] {
			continue
		}
		seen[rel] = true
		path := filepath.Join(root, filepath.FromSlash(rel))
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		out = append(out, map[string]any{
			"name": "graph_skills/" + rel,
			"text": string(data),
		})
		if limit > 0 && len(out) >= limit {
			break
		}
	}
	return out
}

func findGraphSkillsRoot() string {
	candidates := []string{}
	if repo := strings.TrimSpace(os.Getenv("FLOW_REPO_ROOT")); repo != "" {
		candidates = append(candidates, filepath.Join(repo, "server", "flow", "graph_skills"))
	}
	if wd, err := os.Getwd(); err == nil {
		for dir := wd; ; dir = filepath.Dir(dir) {
			candidates = append(candidates, filepath.Join(dir, "server", "flow", "graph_skills"))
			parent := filepath.Dir(dir)
			if parent == dir {
				break
			}
		}
	}
	for _, candidate := range candidates {
		if info, err := os.Stat(candidate); err == nil && info.IsDir() {
			return candidate
		}
	}
	return ""
}

func mapsToAnySlice(items []map[string]any) []any {
	out := make([]any, 0, len(items))
	for _, item := range items {
		out = append(out, item)
	}
	return out
}

func mapValue(value any) map[string]any {
	if m, ok := value.(map[string]any); ok {
		return m
	}
	return map[string]any{}
}

func anySliceValue(value any) []any {
	if items, ok := value.([]any); ok {
		return items
	}
	return nil
}

func stringValue(value any) string {
	if s, ok := value.(string); ok {
		return s
	}
	return ""
}

func writeSSE(c *gin.Context, event string, data any) {
	payload, err := json.Marshal(data)
	if err != nil {
		payload = []byte(`{"message":"failed to encode SSE payload"}`)
	}
	_, _ = fmt.Fprintf(c.Writer, "event: %s\ndata: %s\n\n", event, payload)
	if flusher, ok := c.Writer.(http.Flusher); ok {
		flusher.Flush()
	}
}
